### ISSUE TITLE
希望可以增加连按两下cmd+q退出的模式

### ISSUE THREAD

**Issue by ProudBenzene** [lihaoyun6/QDelayer#1]
一直按着cmd+q的话，有时候会唤起_cheatsheet_的界面，有一点不方便。
建议增加一个短时间内连续按两下退出软件的模式，类似Chrome、edge和旧版QQ那样。
谢谢！

**Comment by lihaoyun6** [comment]
> 一直按着cmd+q的话，有时候会唤起_cheatsheet_的界面，有一点不方便。
> 建议增加一个短时间内连续按两下退出软件的模式，类似Chrome、edge和旧版QQ那样。
> 谢谢！

感谢您的宝贵建议, 我会将此功能的支持提上日程. 敬请期待

**Comment by lihaoyun6** [comment]
> 一直按着cmd+q的话，有时候会唤起_cheatsheet_的界面，有一点不方便。
> 建议增加一个短时间内连续按两下退出软件的模式，类似Chrome、edge和旧版QQ那样。
> 谢谢！

已在最新的 v0.1.2 版本中支持了此功能, 更新后在偏好设置中开启"双击代替长按"选项就可以了.

**Comment by ProudBenzene** [comment]
> > 一直按着cmd+q的话，有时候会唤起_cheatsheet_的界面，有一点不方便。
> > 建议增加一个短时间内连续按两下退出软件的模式，类似Chrome、edge和旧版QQ那样。
> > 谢谢！
> 
> 已在最新的 v0.1.2 版本中支持了此功能, 更新后在偏好设置中开启"双击代替长按"选项就可以了.

谢谢您的更新！体验下来双击退出确实更加舒适～
不过我貌似又发现了两个问题：
1. Qdelay开启白名单模式，不给edge浏览器设置，会导致edge原生的双击cmd + q退出失效；
2. 开机启动好像没有效果，最后我通过手动从设置将软件添加到登录项解决。
