### ISSUE TITLE
拦截的提示显示时长有点短

### ISSUE THREAD

**Issue by wang93wei** [lihaoyun6/QDelayer#2]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/6371053/191156969-f2c35e57-9553-4533-92de-53c5da795303.png">

可不可以自定义提示显示的时长啊，，，现在感觉这个时长有点短……

**Comment by lihaoyun6** [comment]
<img width="219" alt="image" src="https://user-images.githubusercontent.com/16348097/192035583-f81a9c71-877c-4a66-a615-81327aec23c0.png">  
在最新的v0.1.3版本中已经添加了相关设置项, 允许用户在一定范围内自定义双击间隔. 请前往更新即可.
