### ISSUE TITLE
多显示器时，提示文字没有在对应显示器显示

### ISSUE THREAD

**Issue by wang93wei** [lihaoyun6/QDelayer#3]
例如，现在有俩显示器，纵向排列

鼠标移动到上方的显示器，提示显示的仍然是在下方的Macbook上显示，而不是外接显示器显示的
<img width="668" alt="image" src="https://user-images.githubusercontent.com/6371053/191157249-5f12c9ba-0a40-4a54-85f1-215a4b6ac0e9.png">

**Comment by lihaoyun6** [comment]
> 例如，现在有俩显示器，纵向排列
> 
> 鼠标移动到上方的显示器，提示显示的仍然是在下方的Macbook上显示，而不是外接显示器显示的

以上问题已经在最新的v0.1.3版本中修复了, 请前往更新即可.
