### ISSUE TITLE
与Edge原生提示不兼容，开机启动疑似失效

### ISSUE THREAD

**Issue by ProudBenzene** [lihaoyun6/QDelayer#4]
您好，我又发现了两个问题：

Qdelay开启白名单模式，不给edge浏览器设置，会导致edge原生的双击cmd + q退出失效；
开机启动好像没有效果，最后我通过手动从设置将软件添加到登录项解决。

还请您修复这两个问题，谢谢！

**Comment by lihaoyun6** [comment]
> 您好，我又发现了两个问题：
> 
> Qdelay开启白名单模式，不给edge浏览器设置，会导致edge原生的双击cmd + q退出失效； 开机启动好像没有效果，最后我通过手动从设置将软件添加到登录项解决。
> 
> 还请您修复这两个问题，谢谢！

以上问题已经在最新的v0.1.3版本中修复了, 请前往更新即可.
