### ISSUE TITLE
pd18两分钟自动停止

### ISSUE THREAD

**Issue by shangyuan0818** [lihaoyun6/QDelayer#5]
pd18貌似加入了过期检测，用pdrunner启动后两分钟不到就自动停止虚拟机，希望修复

**Comment by lihaoyun6** [comment]
鉴于已经有更完美的方案出现, PD Runner已在本月初停止更新, 以后也不会再进行维护.

**Comment by libopenggggg** [comment]
什么方案> 鉴于已经有更完美的方案出现, PD Runner已在本月初停止更新, 以后也不会再进行维护.
