### ISSUE TITLE
拦截cmd+w功能虽然设置为未启动，但实际使用的时候仍然会拦截

### ISSUE THREAD

**Issue by ProudBenzene** [lihaoyun6/QDelayer#6]
拦截cmd+w功能虽然设置为未启动，但实际使用的时候仍然会拦截。
感谢作者的辛苦更新！

**Comment by lihaoyun6** [comment]
> 拦截cmd+w功能虽然设置为未启动，但实际使用的时候仍然会拦截。
> 感谢作者的辛苦更新！

此问题已在最新的 v0.1.4 版本中得到了修复, 请更新即可.
